<?php
return [
  'app_name'     => 'PayrollPro',
  'dashboard'    => 'Dashboard',
  'employees'    => 'Employees',
  'job_titles'   => 'Job Titles',
  'payroll'      => 'Payroll',
  'attendance'   => 'Attendance',
  'leaves'       => 'Leave Management',
  'leave_types'  => 'Leave Types',
  'loans'        => 'Loans',
  'departments'  => 'Departments',
  'users'        => 'Users',
  'reports'      => 'Reports',
  'settings'     => 'Settings',
  'logout'       => 'Logout',
  'login'        => 'Login',
  'welcome'      => 'Welcome',
  'save'         => 'Save',
  'cancel'       => 'Cancel',
  'delete'       => 'Delete',
  'edit'         => 'Edit',
  'add'          => 'Add',
  'view'         => 'View',
  'search'       => 'Search',
  'filter'       => 'Filter',
  'export_pdf'   => 'Export PDF',
  'export_excel' => 'Export Excel',
  'print'        => 'Print',
  'actions'      => 'Actions',
  'status'       => 'Status',
  'active'       => 'Active',
  'inactive'     => 'Inactive',
  'male'         => 'Male',
  'female'       => 'Female',
  'full_time'    => 'Full Time',
  'part_time'    => 'Part Time',
  'contractor'   => 'Contractor',
  'intern'       => 'Intern',

  // Employee fields
  'employee_no'       => 'Employee No.',
  'employee_name'     => 'Employee Name',
  'name_en'           => 'Name (English)',
  'name_ar'           => 'Name (Arabic)',
  'department'        => 'Department',
  'job_title'         => 'Job Title',
  'hire_date'         => 'Hire Date',
  'basic_salary'      => 'Basic Salary',
  'nationality'       => 'Nationality',
  'email'             => 'Email',
  'phone'             => 'Phone',
  'bank_name'         => 'Bank Name',
  'iban'              => 'IBAN',
  'employment_type'   => 'Employment Type',
  'total_employees'   => 'Total Employees',
  'new_this_month'    => 'New This Month',

  // Payroll
  'payroll_period'    => 'Payroll Period',
  'process_payroll'   => 'Process Payroll',
  'approve_payroll'   => 'Approve Payroll',
  'gross_salary'      => 'Gross Salary',
  'net_salary'        => 'Net Salary',
  'total_allowances'  => 'Total Allowances',
  'total_deductions'  => 'Total Deductions',
  'overtime'          => 'Overtime',
  'absent_days'       => 'Absent Days',
  'payment_date'      => 'Payment Date',
  'payslip'           => 'Payslip',
  'draft'             => 'Draft',
  'processing'        => 'Processing',
  'approved'          => 'Approved',
  'paid'              => 'Paid',

  // Allowances & Deductions
  'allowances'        => 'Allowances',
  'deductions'        => 'Deductions',
  'housing_allowance' => 'Housing Allowance',
  'transport_allowance' => 'Transport Allowance',
  'social_insurance'  => 'Social Insurance',
  'income_tax'        => 'Income Tax',
  'holidays'         => 'Holidays',
  'holiday'           => 'Holiday',
  'government_holiday' => 'Government Holiday',
  'religious_holiday' => 'Religious Holiday',
  'company_holiday'   => 'Company Holiday',

  // Attendance
  'present'       => 'Present',
  'absent'        => 'Absent',
  'late'          => 'Late',
  'half_day'      => 'Half Day',
  'check_in'      => 'Check In',
  'check_out'     => 'Check Out',
  'late_minutes'  => 'Late (min)',
  'overtime_hours'=> 'Overtime (hrs)',

  // Leave
  'leave_type'    => 'Leave Type',
  'start_date'    => 'Start Date',
  'end_date'      => 'End Date',
  'days'          => 'Days',
  'reason'        => 'Reason',
  'pending'       => 'Pending',
  'approved_status' => 'Approved',
  'rejected'      => 'Rejected',
  'leave_balance' => 'Leave Balance',
  'remaining'     => 'Remaining',

  // Dashboard
  'payroll_summary'  => 'Payroll Summary',
  'dept_breakdown'   => 'Department Breakdown',
  'recent_payrolls'  => 'Recent Payrolls',
  'pending_leaves'   => 'Pending Leave Requests',
  'total_payroll'    => 'Total Payroll',
  'currency'         => 'KWD',

  // Settings
  'company_settings'   => 'Company Settings',
  'company_name'       => 'Company Name',
  'company_address'    => 'Company Address',
  'tax_rate'           => 'Tax Rate (%)',
  'social_ins_rate'    => 'Social Insurance Rate (%)',
  'overtime_rate'      => 'Overtime Rate (multiplier)',
  'work_days_month'    => 'Working Days / Month',
  'payroll_day'        => 'Payroll Day',
  'save_settings'      => 'Save Settings',

  // Messages
  'saved_success'  => 'Saved successfully.',
  'deleted_success'=> 'Deleted successfully.',
  'error_occurred' => 'An error occurred. Please try again.',
  'confirm_delete' => 'Are you sure you want to delete this record?',
  'no_records'     => 'No records found.',
  'loading'        => 'Loading...',
  'year'           => 'Year',
  'month'          => 'Month',
  'total'          => 'Total',
  'amount'         => 'Amount',
  'percentage'     => 'Percentage',
  'notes'          => 'Notes',
  'created_at'     => 'Created At',
  
  // Bonuses
  'bonuses'        => 'Bonuses & Commissions',
  'bonus_type'     => 'Bonus Type',
  'performance_bonus' => 'Performance Bonus',
  'sales_commission' => 'Sales Commission',
  'project_bonus'  => 'Project Bonus',
  'signing_bonus'  => 'Signing Bonus',
  'referral_bonus' => 'Referral Bonus',
  'year_end_bonus' => 'Year-End Bonus',
  'description'    => 'Description',
  'approve'        => 'Approve',
  'reject'         => 'Reject',
  'mark_paid'      => 'Mark as Paid',
  
  // Gratuity
  'gratuity'       => 'Gratuity / End of Service',
  'calculate_gratuity' => 'Calculate Gratuity',
  'calculation_date' => 'Calculation Date',
  'termination_date' => 'Termination Date',
  'years_of_service' => 'Years of Service',
  'last_salary'    => 'Last Salary',
  'gratuity_amount' => 'Gratuity Amount',
  'calculation_method' => 'Calculation Method',
  'kuwait_labor_law' => 'Kuwait Labor Law',
  'custom'         => 'Custom',
  
  // Reports
  'yearly_summary' => 'Yearly Summary',
  'year_over_year' => 'Year-over-Year Comparison',
  'employee_history' => 'Employee History',
  'department_report' => 'Department Report',
  'change_type'    => 'Change Type',
  'field_name'     => 'Field',
  'old_value'      => 'Old Value',
  'new_value'      => 'New Value',
  'changed_by'     => 'Changed By',
];
